env typo fixed

diff --git a/.github/workflows/helm-ci.yml b/.github/workflows/helm-ci.yml
--- a/.github/workflows/helm-ci.yml
+++ b/.github/workflows/helm-ci.yml
@@ -8,8 +8,7 @@ on:
   pull_request:
     paths:
       - 'infra/helm/**'
-    
-  
+
 jobs:
   helm_template:
     name: Helm Check
@@ -18,36 +17,40 @@ jobs:
     steps:
     - name: Checkout Code
       uses: actions/checkout@v4
-      with:
-       ref: ${{ github.event.pull_request.head.sha }}
-
 
     - name: Set up Helm
       uses: azure/setup-helm@v3
       with:
         version: 'latest'
 
-    - name: Lint Helm Chart
-      run: |
-        helm lint  helm lint ./infra/helm/charts/* -f ./infra/helm/env/values-dev.yaml
-        if [ $? -ne 0 ]; then
-          echo "Error in Helm lint"
-          exit 1
-        else
-          echo "Lint is successful"  
-        fi
-      
-    - name: Helm Template for All Charts
+    - name: Lint Helm Charts
       run: |
         for chart in ./infra/helm/charts/*; do
-          if [ -d "$chart" ]; then
-            echo "Processing $(basename $chart)..."
-            helm template $(basename $chart) $chart -f ./infra/helm/env/values-dev.yaml
+          if [ -d "$chart" ] && [ -e "$chart/Chart.yaml" ]; then
+            echo "Linting $(basename $chart)..."
+            helm lint $chart -f ./infra/helm/env/values-dev.yaml
             if [ $? -ne 0 ]; then
-              echo "Error in helm template for $(basename $chart)"
+              echo "Error in Helm lint for $(basename $chart)"
               exit 1
             fi
+          else
+            echo "Skipping $(basename $chart), not a chart directory or Chart.yaml missing"
           fi
         done
-        echo "All Helm charts processed successfully"
-        exit 0
+        echo "Linting completed successfully"
+
+    - name: Template Helm Charts
+      run: |
+        for chart in ./infra/helm/charts/*; do
+          if [ -d "$chart" ] && [ -e "$chart/Chart.yaml" ]; then
+            echo "Templating $(basename $chart)..."
+            helm template $(basename $chart) $chart -f ./infra/helm/env/values-dev.yaml
+            if [ $? -ne 0 ]; then
+              echo "Error in Helm template for $(basename $chart)"
+              exit 1
+            fi
+          else
+            echo "Skipping $(basename $chart), not a chart directory or Chart.yaml missing"
+          fi
+        done
+        echo "Templating completed successfully"
