dabaging

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,63 +1,99 @@
-name: New Release
+name: Promote and Build Microservice
 
 on:
-  workflow_dispatch:
+  workflow_call:
     inputs:
+      service-name:
+        required: true
+        type: string
       version-type:
-        description: 'Type of version increment to apply (major, minor, patch)'
         required: true
-        default: 'patch'
-      promote-echo-server:
-        description: 'Promote Echo Server?'
+        type: string
+      service-path:
         required: true
-        type: boolean
-      promote-frontend:
-        description: 'Promote Frontend?'
-        required: true
-        type: boolean
+        type: string
 
 permissions:
   contents: write
   packages: write
 
-env:
-  REGISTRY: ghcr.io
-
 jobs:
-  promote-echo-server:
-    if: ${{ github.event.inputs.promote-echo-server }}
-    uses: ./.github/workflows/promote-build.yml
-    with:
-      service-name: echo-server
-      version-type: ${{ github.event.inputs.version-type }}
-      service-path: ./app/echo-server
-
-
-  promote-frontend:
-    if: ${{ github.event.inputs.promote-frontend }}
-    uses: ./.github/workflows/promote-build.yml
-    with:
-      service-name: frontend
-      version-type: ${{ github.event.inputs.version-type }}
-      service-path: app/frontend
-
-  create-release:
-    needs: [promote-echo-server, promote-frontend]
+  promote-and-build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0
+          fetch-depth: 0  # Fetch all history for proper rebase and push
 
       - name: Set up Git
         run: |
           git config --global user.email "${{ github.actor }}@users.noreply.github.com"
           git config --global user.name "${{ github.actor }}"
 
-      - name: Create GitHub Release
-        if: ${{ github.event.inputs.version-type == 'minor' || github.event.inputs.version-type == 'major' }}
+      - name: Upgrade version
+        id: upgrade_version 
         run: |
-          sudo apt-get install -y gh
-          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
-          gh release create ${{ env.new_version }} --title "Release ${{ env.new_version }}" --notes "## Changes in this release\n\n- Version update to ${{ env.new_version }}"
+          set -e  # Exit immediately if a command exits with a non-zero status
+
+          VERSION_FILE="${{ inputs.service-path }}/version.txt"
+          if [ ! -f "$VERSION_FILE" ]; then
+            echo "Version file not found: $VERSION_FILE"
+            exit 1
+          fi
+
+          currentVersion=$(cat $VERSION_FILE)
+
+          # Extract the major, minor, and patch components
+          IFS='.' read -r -a versionArray <<< "$currentVersion"
+          major="${versionArray[0]}"
+          minor="${versionArray[1]}"
+          patch="${versionArray[2]}"
+
+          VERSION_TYPE="${{ inputs.version-type }}"
+
+          case $VERSION_TYPE in
+            major)
+              major=$((major + 1))
+              minor=0
+              patch=0
+              ;;
+            minor)
+              minor=$((minor + 1))
+              patch=0
+              ;;
+            patch)
+              patch=$((patch + 1))
+              ;;
+          esac
+
+          # Form the new version string
+          newVersion="$major.$minor.$patch"
+
+          # Update the version in the file
+          echo "$newVersion" > $VERSION_FILE
+
+          # Set the new version in the output
+          echo "new_version=$newVersion" >> $GITHUB_ENV
+
+          # Commit the changes
+          git add $VERSION_FILE
+          git commit -m "Upgrade version to $newVersion"
+
+          # Push the changes to the current branch
+          git push origin HEAD:${{ github.ref }}
+
+      - name: Log into GitHub Packages
+        uses: docker/login-action@v1
+        with:
+          registry: docker.pkg.github.com
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v5
+        with:
+          context: ${{ inputs.service-path }}
+          file: ${{ inputs.service-path }}/Dockerfile
+          push: true
+          tags: docker.pkg.github.com/${{ github.repository_owner }}/${{ inputs.service-name }}:${{ env.new_version }}
